services:
  web:
    build: .
    command: gunicorn blog_website.wsgi:application --bind 0.0.0.0:#
    ports:
      - "#:#"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_NAME=#
      - DATABASE_USER=#
      - DATABASE_PASSWORD=#
      - DATABASE_HOST=#

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: #
      POSTGRES_USER: #
      POSTGRES_PASSWORD: #
    command: postgres -c listen_addresses='*'  # Aceptar conexiones de cualquier IP 
    ports:
      - "#:#"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
