# Generated by Django 5.1.7 on 2025-05-08 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_post', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.CharField(max_length=1000, verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
                ('public', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
