# Generated by Django 5.1.7 on 2025-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='default-slug', max_length=150, unique=True, verbose_name='URL amigable'),
            preserve_default=False,
        ),
    ]
