# Generated by Django 5.1.7 on 2025-05-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.CharField(max_length=1000, verbose_name='Contenido')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='URL amigable')),
                ('visible', models.BooleanField(default=True, verbose_name='¿Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el:')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='public',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
