# Generated by Django 5.1.7 on 2025-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_remove_blog_public_remove_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=100000, verbose_name='Contenido'),
        ),
    ]
