# Generated by Django 5.1.7 on 2025-05-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_comentarios_mis_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.comentarios'),
        ),
    ]
