# Generated by Django 5.1.7 on 2025-05-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_alter_comentarios_autor_alter_blog_autor_and_more'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mis_posts',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_posts', to='pages.blog'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='pages.blog'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
