# Generated by Django 5.1.7 on 2025-05-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_alter_mis_posts_blog_alter_comentarios_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mis_posts',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Mis_Posts',
        ),
    ]
